### ISSUE TITLE
Error: "radialGauge" is not a chart type.

### ISSUE THREAD

**Issue by sante85** [pandameister/chartjs-chart-radial-gauge#1]
i have copied code pen in angular component
and js 
in angular.json script: []

but this is the error: 

Error: "radialGauge" is not a chart type.

**Comment by sante85** [comment]
yes, but in typescript you need specify require, and not import (es6 style)

I'll expect that i write:

import * as Chart from 'chart.js'
import * as RadialGauge from 'chartjs-chart-radial-gauge'

instead

const Chart = require('chart.js');
require('chartjs-chart-radial-gauge')

this is old style...

It's clear?

Best regards

**Comment by pandameister** [comment]
closing as it works as expected in typescript
