### ISSUE TITLE
subText not working

### ISSUE THREAD

**Issue by CamilleGrs** [pandameister/chartjs-chart-radial-gauge#14]
Hi,
I really like this chart but I can't get the subText to work. Is there any specific parameter I need to pass a subText?
Here is my config variable:

var config = {
 type: "radialGauge",
 data: {
  labels: ["Low"],
  datasets: [
   {
    data: [value],
    backgroundColor: [color],
    borderWidth: 0,
    label: "Score"
   }
  ]
 },
 options: {
  responsive: true,
  domain: [0, 3085],
  centerPercentage: 80,
  roundedCorners: true,
  centerArea: {
   text: value,
   subText: "Low"
  }
 }
};

**Comment by pandameister** [comment]
@CamilleGrs That config looks ok, is there any errors in the browser dev console?


if you add this to the config in `samples/basic.html`:

```js
centerArea: {
  subText: 'x',
 },
```

you should see the sub text present

**Comment by CamilleGrs** [comment]
Hi @pandameister 
No, I don't have any error in the dev console.
I tried to remove the text:value and try the exact array you sent but I still don't get anything on my chart.

**Comment by pandameister** [comment]
@CamilleGrs I updated latest npm version to support the subtitle, make sure you have `chartjs-chart-radial-gauge@1.1.0`. Also you should be able to see it in the pen now:

https://codepen.io/pandameister/pen/OrJyYr
