### ISSUE TITLE
Gradient trackColor applies to data track as well as background track

### ISSUE THREAD

**Issue by olliejm** [pandameister/chartjs-chart-radial-gauge#2]
I'm trying to apply a gradient to the data track as is shown in the medium article.

I've used the following code:

```js
const gradient = ctx.createLinearGradient(0, 100, 170, 0);

gradient.addColorStop(0, startColor);
gradient.addColorStop(1, endColor);

config.options.trackColor = gradient;
```

But I end up with the gradient being applied to both foreground and background track:
![issue](https://i.imgur.com/Xg5ddAh.png)

The expected result was more like:
![expected](https://cdn-images-1.medium.com/max/1600/1*KFbTSS5nCMF0-jdPqO2_fQ.gif)

**Comment by pandameister** [comment]
@olliejm I'll create a bug for this, thanks

**Comment by pandameister** [comment]
@olliejm as a work around if you specify the background color for the dataset it should work:

see: https://codepen.io/pandameister/pen/MxMbWd
