### ISSUE TITLE
Display float type values

### ISSUE THREAD

**Issue by deviashin** [pandameister/chartjs-chart-radial-gauge#9]
Hello!
Thanks for this!

Tell me, please, how to display floating point values in the center of a circle? Initially, data of the String type, for example, "28.73", but after displaying according to mathematical rules, "29" is displayed, is rounded up.
How to fix this?

**Comment by pandameister** [comment]
@deviashin you can specify a custom function in the options to format the center value as you like

eg:
```javascript
options: {
    centerArea: {
            text: function (value) { return value.toFixed(2); }
    }
}
`

**Comment by deviashin** [comment]
Thank you very much!

I combined your methods and got the desired result
Now in the center of the circle displays a floating point value and a degree of Celsius

`centerArea: {
             text: function (value, options) {
             return value.toFixed (2) + '°C';
             }
         }`

**Comment by nitinkg7** [comment]
Same here. Decimal points are always rounded to .00. This should be fixed.
